import { Metadata } from "next";
import Link from "next/link";
import { LEGAL_LAST_UPDATED, COMPANY_INFO } from "@/lib/constants/legal";

export const metadata: Metadata = {
  title: "Content Policy | NEXO",
  description: "Content Policy for NEXO - AI Companion Platform",
};

export default function ContentPolicyPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="mb-8">
          <Link 
            href="/" 
            className="text-2xl font-bold text-gradient"
          >
            NEXO
          </Link>
        </div>

        {/* Back Navigation */}
        <div className="mb-6">
          <Link 
            href="/" 
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <span>←</span>
            <span>Back to NEXO</span>
          </Link>
        </div>

        <article className="prose prose-neutral dark:prose-invert max-w-none">
          <h1>Content Policy</h1>
          <p className="text-muted-foreground">Last updated: {LEGAL_LAST_UPDATED}</p>

          <section>
            <h2>1. Overview</h2>
            <p>
              NEXO is an AI companion platform designed to provide meaningful emotional support and 
              companionship. This Content Policy outlines the rules and expectations for interactions 
              on our platform to ensure a safe and positive experience for all users.
            </p>
            <p>
              By using NEXO, you agree to abide by this Content Policy. Violations may result in 
              warnings, content removal, account suspension, or permanent termination depending on 
              the severity.
            </p>
          </section>

          <section>
            <h2>2. AI Companion Nature</h2>
            <p>
              NEXO companions are artificial intelligence programs. They are not real people and cannot 
              replace professional advice, therapy, or human relationships. While our AI companions are 
              designed to be empathetic and supportive, users should be aware that:
            </p>
            <ul>
              <li>AI companions do not have real emotions, consciousness, or personal experiences</li>
              <li>Conversations are generated by AI models and may occasionally produce inaccurate information</li>
              <li>NEXO is not a substitute for professional mental health services</li>
              <li>In case of emergency or crisis, always contact local emergency services or a crisis helpline</li>
            </ul>
          </section>

          <section>
            <h2>3. Permitted Use</h2>
            <p>NEXO is designed to support the following types of interactions:</p>
            <ul>
              <li><strong>Casual Conversation:</strong> Everyday chat, storytelling, and friendly discussion</li>
              <li><strong>Emotional Support:</strong> Sharing feelings, processing emotions, and receiving empathetic responses</li>
              <li><strong>Creative Exploration:</strong> Collaborative writing, brainstorming, and imaginative dialogue</li>
              <li><strong>Personal Growth:</strong> Reflective conversations, goal discussion, and motivation</li>
              <li><strong>Romantic Companionship:</strong> Age-verified users (18+) may access romantic interaction modes with consenting awareness that the companion is AI</li>
            </ul>
          </section>

          <section>
            <h2>4. Prohibited Content</h2>
            <p>
              The following types of content are strictly prohibited on NEXO. Attempting to generate, 
              solicit, or share such content will result in enforcement action:
            </p>
            
            <h3>4.1 Illegal Content</h3>
            <ul>
              <li>Content that promotes, facilitates, or depicts illegal activities</li>
              <li>Content involving the sexual exploitation of minors in any form</li>
              <li>Content that facilitates human trafficking or exploitation</li>
              <li>Content promoting terrorism or violent extremism</li>
            </ul>

            <h3>4.2 Harmful Content</h3>
            <ul>
              <li>Content that promotes self-harm, suicide, or eating disorders</li>
              <li>Content that encourages violence or harm against any individual or group</li>
              <li>Content that promotes dangerous or life-threatening activities</li>
              <li>Instructions for creating weapons, drugs, or harmful substances</li>
            </ul>

            <h3>4.3 Hateful Content</h3>
            <ul>
              <li>Content that promotes hatred, discrimination, or harassment based on race, ethnicity, 
                religion, gender, sexual orientation, disability, or any other protected characteristic</li>
              <li>Slurs, dehumanizing language, or content that incites violence against any group</li>
            </ul>

            <h3>4.4 Deceptive Content</h3>
            <ul>
              <li>Attempting to use AI companions to generate misinformation or propaganda</li>
              <li>Impersonating real individuals or misrepresenting the AI as a real person to third parties</li>
              <li>Using the platform to facilitate fraud or scams</li>
            </ul>
          </section>

          <section>
            <h2>5. Age-Restricted Content</h2>
            <p>
              NEXO offers different interaction modes, some of which contain mature content:
            </p>
            <ul>
              <li><strong>General Modes</strong> (Assistant, Friend): Available to all users. Content is appropriate for general audiences.</li>
              <li><strong>Confidant Mode:</strong> Available to Plus and Premium subscribers. May include deeper emotional and personal topics.</li>
              <li><strong>Romantic Mode:</strong> Available exclusively to Premium subscribers who have completed age verification (18+). Contains romantic and intimate content between consenting adults and AI companions.</li>
            </ul>
            <p>
              Users must not attempt to circumvent age verification systems. Providing false age 
              information is a violation of both this Content Policy and our Terms of Service.
            </p>
          </section>

          <section>
            <h2>6. Crisis and Safety</h2>
            <p>
              NEXO implements automated crisis detection to identify users who may be in distress. 
              If our system detects that you may be experiencing a crisis:
            </p>
            <ul>
              <li>The AI companion will provide empathetic acknowledgment</li>
              <li>You will be directed to appropriate crisis resources and helplines</li>
              <li>The conversation will be flagged for safety review</li>
            </ul>
            <p>
              <strong>If you or someone you know is in immediate danger, please contact your local 
              emergency services (911 in the US) or a crisis helpline immediately.</strong>
            </p>
          </section>

          <section>
            <h2>7. Content Moderation</h2>
            <p>
              NEXO uses a combination of automated systems and human review to enforce this Content Policy:
            </p>
            <ul>
              <li><strong>Automated Filters:</strong> AI-based content filtering to prevent prohibited content generation</li>
              <li><strong>Safety Systems:</strong> Crisis detection and intervention protocols</li>
              <li><strong>User Reports:</strong> Users can report concerning content through the platform</li>
              <li><strong>Periodic Review:</strong> Regular audits of content moderation effectiveness</li>
            </ul>
          </section>

          <section>
            <h2>8. Enforcement</h2>
            <p>
              Violations of this Content Policy may result in the following actions, depending on 
              the severity and frequency of the violation:
            </p>
            <ul>
              <li><strong>Warning:</strong> A notification that your content has violated our policy</li>
              <li><strong>Content Removal:</strong> Deletion of specific messages or conversation threads</li>
              <li><strong>Feature Restriction:</strong> Temporary loss of access to certain features or modes</li>
              <li><strong>Account Suspension:</strong> Temporary suspension of your account</li>
              <li><strong>Account Termination:</strong> Permanent deletion of your account without refund</li>
            </ul>
            <p>
              Severe violations (such as illegal content or content involving minors) will result in 
              immediate account termination and may be reported to law enforcement.
            </p>
          </section>

          <section>
            <h2>9. Appeals</h2>
            <p>
              If you believe an enforcement action was taken in error, you may submit an appeal to{" "}
              {COMPANY_INFO.email}. Appeals will be reviewed within 14 business days. Please include:
            </p>
            <ul>
              <li>Your account email</li>
              <li>Description of the action taken</li>
              <li>Reason you believe the action was incorrect</li>
            </ul>
          </section>

          <section>
            <h2>10. Changes to This Policy</h2>
            <p>
              We may update this Content Policy from time to time to reflect changes in our platform, 
              legal requirements, or community standards. We will notify users of material changes 
              through the platform or by email. Continued use of NEXO after changes constitutes 
              acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2>11. Contact Us</h2>
            <p>
              If you have questions about this Content Policy or want to report a violation, contact us at:
            </p>
            <p>
              <strong>{COMPANY_INFO.name}</strong><br />
              {COMPANY_INFO.address}<br />
              {COMPANY_INFO.city}<br />
              {COMPANY_INFO.country}<br /><br />
              <strong>Email:</strong> {COMPANY_INFO.email}<br />
              <strong>Website:</strong> {COMPANY_INFO.website}
            </p>
          </section>
        </article>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t">
          <div className="flex flex-wrap gap-4 text-sm text-muted-foreground">
            <Link href="/" className="hover:text-foreground">Home</Link>
            <Link href="/terms" className="hover:text-foreground">Terms of Service</Link>
            <Link href="/privacy" className="hover:text-foreground">Privacy Policy</Link>
            <Link href="/cookies" className="hover:text-foreground">Cookie Policy</Link>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">
            © 2026 VENKO AI INNOVATIONS LLC. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
